### PR TITLE
[ISSUE 51] Add support for (m)TLS

### PR DESCRIPTION
**Pull request by jluehe**
Sample invocations:

TLS:
```
% java -Djavax.net.ssl.trustStore=<trust_store> -Djavax.net.ssl.trustStorePassword=<trust_store_password> -Djavax.net.debug=ssl:all -jar jmxterm-1.0.1-SNAPSHOT-uber.jar -l <host>:<jmx_port> -u <jmx_user> -p <jmx_password>
```
mTLS:
```
% java -Djavax.net.ssl.trustStore=<trust_store> -Djavax.net.ssl.trustStorePassword=<trust_store_password> -Djavax.net.ssl.keyStore=<key_store> -Djavax.net.ssl.keyStorePassword=<key_store_password> -Djavax.net.debug=ssl:all -jar jmxterm-1.0.1-SNAPSHOT-uber.jar -l <host>:<jmx_port> -u <jmx_user> -p <jmx_password>
```

### CODE REVIEW

**Comment by jluehe** [comment]
@vroyer, this did the trick for me. Please confirm from your end as well. 
@jiaqi, I will update docs and add unit test as needed.

**Comment by jiaqi** [comment]
Thanks for working on this. I'll take a look and do some verification but it looks very promising.

**Comment by jluehe** [comment]
Thanks, @jiaqi - I just added comments describing the circumstances under which each of the env.put calls for SslRMIClientSocketFactory is necessary.

I also did some further testing and found that the second call should probably made conditional - it is required only iff the server was started with "com.sun.management.jmxremote.registry.ssl=true", and will lead to this handshake error if it wasn't (that is, only "com.sun.management.jmxremote.ssl=true" was used):
```
[Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
	javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
	at org.cyclopsgroup.jmxterm.cc.SessionImpl.doConnect(SessionImpl.java:64)
	at org.cyclopsgroup.jmxterm.cc.SessionImpl.connect(SessionImpl.java:39)
	at org.cyclopsgroup.jmxterm.cc.CommandCenter.connect(CommandCenter.java:103)
	at org.cyclopsgroup.jmxterm.boot.CliMain.execute(CliMain.java:127)
	at org.cyclopsgroup.jmxterm.boot.CliMain.main(CliMain.java:37)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
	javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake]
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
	... 6 more
Caused by: java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
	javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:307)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:338)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:112)
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
	... 11 more
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:757)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:229)
	... 15 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	... 22 more
```
I am going to refine my PR accordingly ...

**Comment by jluehe** [comment]
@jiaqi, I have completed all my changes. Please review and let me know if you have any questions.

Summary:

Standard JMX client support will automatically use **Ssl**RMIClientSocketFactory if truststore/keystore system properties have been specified, so (m)TLS normally works out of the box. There's only one caveat, though, which is mentioned in the code snippet of section **Connecting to the MBean Server** at https://docs.oracle.com/javadb/10.10.1.2/adminguide/radminjmxcode.html:
```
    //env.put("com.sun.jndi.rmi.factory.socket", 
    //    new SslRMIClientSocketFactory());  // uncomment if needed
```
and this comment which follows it:
```
Note: Not specifying SslRMIClientSocketFactory when required may result in the error message java.rmi.ConnectIOException: non-JRMP server at remote endpoint.
```
This is the connection error that @vroyer had run into, when he created the issue.

I have added a new cmd line option "-s", which, if specified, will cause the above environment attribute to be added.

I have tested TLS and mTLS, both with and without password authentication.

I have also performed these negative tests:

- Launch server with "-Dcom.sun.management.jmxremote.registry.ssl=false" + specify "-s" on jmxterm cmd line -> Connection fails with "javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake]" error, as expected

- Launch server with "-Dcom.sun.management.jmxremote.registry.ssl=true" and omit "-s" from jmxterm cmd line -> Connection fails with "Caused by: java.rmi.ConnectIOException: non-JRMP server at remote endpoint" error, as expected

**Comment by jluehe** [comment]
@jiaqi, please let me know if you have any questions, and I will gladly answer them. Thanks!

**Comment by jluehe** [comment]
Thank you, @jiaqi

**Pull request merged**
